config/payment.php
src/Drivers/Behpardakht/Behpardakht.php

i think there is extra arguments in verify function for call Behpardakht soap functions. 
exp: 
- bpVerifyRequest($data, $this->settings->apiNamespaceUrl)
- bpReversalRequest($data, $this->settings->apiNamespaceUrl)
- bpSettleRequest($data, $this->settings->apiNamespaceUrl)
**$this->settings->apiNamespaceUrl**  it has no effect on the operation

fix Behpardakht verify function (remove apiNamespaceUrl from Behpardakht driver)

---

src/Drivers/Pasargad/Utils/RSA.php

this commit fixes below issue on latest php versions
Use of undefined constant BCCOMP_LARGER - assumed 'BCCOMP_LARGER' (this will throw an Error in a future version of PHP)

fix: move constant valuse inside class

---

src/Drivers/Asanpardakht/Asanpardakht.php

Instead of using Asanpardakht decrypt method, verify was using laravel decrypt method which was causing problem

fix asanpardakht

---

src/Drivers/Irankish/Irankish.php

irankish callback come with POST method. but you get `referenceId` from GET method. i'm changed it to `Request::input('referenceId')` so now can get this from request.

fix irankish driver. change request from get to input

---

src/Drivers/Zibal/Zibal.php

Added optional allowedCards value to the $data array in Zibal driver.
This addition allows users to send optional allowed bank cards for their zibal payment.

Added optional allowedCards value to Zibal driver.

---

src/Drivers/Saman/Saman.php

Add additional payment info to receipt `detail` bag for Saman driver
new additional fields are:
- traceNo
- referenceNo
- transactionId
- cardNo
they are available via `$receipt->getDetail()` method
This pull request is related to 
https://github.com/shetabit/payment/issues/168
If …

Add additional payment info to receipt for Saman driver

---

src/Drivers/Behpardakht/Behpardakht.php

context array must passed to SoapClient not bpPayRequest method to work correctly in all situation.
When the http2 is activated on server, the server doesn't let the SoapClient to transfer data to shaparak(Behpardakht) server.

pass context array to SoapClient

---

src/Drivers/Zarinpal/Strategies/Normal.php

There is no error text in Zarrinpal portal when confirming with code 101, so the process of showing an error in this case is different.

verif zarinpal exception with 101 status

---

src/RedirectionForm.php

This will fix Deprecated error in PHP 8.1
`PHP Deprecated:  Return type of Shetabit\Multipay\RedirectionForm::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice`

[PHP 8.1] Set jsonSerialize() return type to match interface

---

src/Drivers/Pasargad/Pasargad.php
src/Drivers/Sadad/Sadad.php

Set `LocalDateTime` param to Asia/Tehran timezone for sadad bank driver
Sadad bank driver get tehran LocalDateTime. if we send another date time sadad gateway return an error.

Set `LocalDateTime` param to Asia/Tehran timezon for sadad bank driver

---

src/Drivers/Sadad/Sadad.php

Use payment_identity from invoice details if present otherwise use default settings
For some purpose may need to use different payment identities.

Set dynamic Payment Identity for Sadad

---

src/Drivers/Zarinpal/Strategies/Normal.php
src/Drivers/Zarinpal/Strategies/Sandbox.php
src/Drivers/Zarinpal/Strategies/Zaringate.php

طبق صحبت‌هایی که اینجا زده شد (https://github.com/shetabit/multipay/pull/196) و طبق مقدار قبلی که بوده (https://github.com/shetabit/multipay/pull/196/commits/de7a1d850a369c4c2f97d69c5a024497609398e8#diff-4d66250a162e69f366657eaf26985d035d3aab8d7d92b362a4cce6608573b871) به نظر میاد توی درگاه زرین پال mode های zaringate و sandbox واحد قیمتی‌شون تومان هست ولی برای normal همون ریال اکی هستش و برای اطمینان بیشتر currency هم طبق مستندات (https://www.zarinpal.com/docs/paymentGateway/connectToGateway.html) فرستاده میشه.

Fix zaringate and sandbox currencies

---

src/Payment.php

طبق مشکلی که اینجا گفته شد (https://github.com/shetabit/multipay/pull/196#issuecomment-1605948372) در صورتی که کاربر کانفیگ جدید رو پابلیش نکنه به خطا خواهد خورد بابت همین مقدار کانفیگ کاربر با مقادیر پیش‌فرض درایور مرج شده تا خطا ایجاد نشه.

Merge default configs with user config

---

src/Drivers/Zibal/Zibal.php

[Fixed the bug described in issues 203](https://github.com/shetabit/multipay/issues/203)

Fix: order ID is returned instead of reference ID in Zibal

---

config/payment.php
src/Drivers/Toman/Toman.php

این روزا فروشگاه ها برای اینکه بتوانند در سایت ترب فعالیت کنند، باید از درگاه امن تومن استفاده کنند.
درگاه تومن به درستی روی پکیج پیاده و تست شد.

اضافه کردن درگاه تومن

---

src/Drivers/Zarinpal/Strategies/Normal.php

Store details such as `card_pan`, `card_hash`, `fee`, `fee_type`, `order_id` and `message` in payment verification method of Zarinpal normal API
It stores the information returned by Zarinpal so that the clients could use those.
These changes are based on the [Zarinpal docuementation](https://www.zarinpal.com/docs/paymentGateway/connectToGateway.html#%D8%A7%D8%B9%D8%AA%D8%A8%D8%A7%D8%B1-%D8%B3%D9%86%D8%AC%DB%8C).
Tests are done with real payments in which the details of the payments mentioned above are returned by `verify` method of `Shetabit\Payment\Facade\Payment` class.

Store all details given by Zarinpal payment verification Rest API

---

src/Drivers/Digipay/Digipay.php

In all drivers, there is a property called settings that should be an object. All drivers treat it as an object. But, in the digipay driver, the cast operation is missing in the constructor. 
i cast settings property to object inside __construct.
I have pushed the fix to a new branch called fix-digipay-settings-type.

the settings property must be an object, not an array.

---

src/Drivers/Parsian/Parsian.php

Hi,
In this PR, I applied some advice from the bank to the `parsian` gateway. The changes include:
- Changing the redirect method from `POST` to `GET`.
- Passing the `Originator` key as the user's phone number (check the key with name such as phone, cellphone, and mobile in the details).
I also added a comment: 
**The bank suggests that an English description is better.**
For further details, you can refer to the [documentation](https://pec.shaparak.ir/NewIPGServices/Sale/SaleService.asmx?wsdl).
```xml
<s:complexType name="ClientPaymentRequestDataBase">
<s:sequence>
<s:element minOccurs="0" maxOccurs="1" name="LoginAccount" type="s:string"/>
<s:element minOccurs="1" maxOccurs="1" name="Amount" type="s:long"/>
<s:element minOccurs="1" maxOccurs="1" name="OrderId" type="s:long"/>
<s:element …
```

Fix parsian gateway

---

README-FA.md
README-ZH.md
README.md
composer.json
composer.lock
config/payment.php
src/Drivers/Jibit/Jibit.php
src/Drivers/Jibit/JibitClient.php

Introduced **Jibit** driver to the package. 
The driver is using a file cache utility class for enhanced performance and security by caching access and refresh tokens, as detailed in the Jibit documentation linked below:
https://napi.jibit.ir/ppg/v3/static/docs/index.html#jwt_access_tokens

Add Jibit Gateway

---

config/payment.php
src/Drivers/Digipay/Digipay.php

Hi,
This PR refactors the `Digipay` gateway to the new version of the API. It includes the following changes:
- Changed `apiPaymentUrl`. Reference: [2.1. Address](https://docs.mydigipay.com/upg.html#_address_2).
- Deleted `apiPaymentUrl`. the `purchase` method to return `redirectUrl`, which the user should redirect to. Reference: [2.5. Response fields](https://docs.mydigipay.com/upg.html#_response_fields_2).
- Fixed DocBlock of the `client` properties.
- Changed the hard-coded key of Guzzle with a constant from the `\GuzzleHttp\RequestOptions` class.
- In the `verify` method, pass `type` value from request to api url.
- Added all returned data from the gateway to the `Receipt` class. Reference: [purchase_verify](https://docs.mydigipay.com/upg.html#_purchase_verify).
If further description …

Refactor digipay gateway

---

src/Drivers/Parsian/Parsian.php

This request is created because when we use the Parsian gateway as an API, the response we receive is always a canceled user response.
While the transaction is successfully carried out, upon further investigation, I found a line of code that retrieves the token from the POST method, even though we had set the token in the config. By modifying this line, no more errors are displayed, and the issue is resolved.
I update this line:
`$token = Request::input('Token')`
to
`$token = $this->invoice->getTransactionId() ?? Request::input('Token');`
Now if user set transaction_id from config, we go to next step.
issu link: https://github.com/shetabit/multipay/issues/243
`fixes #243`

Get transaction token from user's config instead of POST method

---

README-FA.md
README-ZH.md
README.md
config/payment.php
src/Drivers/SnappPay/SnappPay.php

Hi,
This pull request adds the `Snapp Pay` gateway, which facilitates installment payments. When creating a transaction, you need to pass the basket details to the gateway. The image below illustrates a simple basket with the required data.
<div dir="rtl">
```
🔹گایدلاین ارسال دیتا در سرویس پیمنت توکن 🔹
➖مقادیر شامل در discountAmount :
کارت هدیه + کد تخفیف + امتیاز کاربر + کوپن
➖مقادیر شامل در externalSourceAmount :
کیف پول کاربر
➖ مقادیر شامل در shippingAmount :
بسته بندی + کادو پیچ + هزینه ارسال + هزینه بسته بندی محرمانه
➖ مقادیر شامل در totalAmount :
حاصل جمع مبالغ آیتم ها با در نظر گرفتن تعداد و هزینه tax و shipping
```
</div>
This driver includes the following methods:
- **eligible**: Ensures that you can offer the credit option to users.
- **settle**: Finalizes the payment after the …

Add `Snapp Pay` driver

---

config/payment.php
src/Drivers/Digipay/Digipay.php

Hi,
This pull request adds two custom methods to the Digipay Gateway:
- [Purchase Reverse](https://docs.mydigipay.com/upg.html#_purchase_reverse)
- [Purchase Delivery](https://docs.mydigipay.com/upg.html#_purchase_delivery)
Additionally, only the base URL is defined in the config file, while sub-URLs are added as constants in the class.
This pull request should be merged after #230.

Add Custom Methods to Digipay Gateway 

---

src/Drivers/SnappPay/SnappPay.php

SnappPay Receipt is being created with `digipay` driver name. I changed that to `snapppay`.

Fix driver name used for creating SnappPay Receipt

---

src/Drivers/SnappPay/SnappPay.php

Currently, all SnappPay endpoints **except `/oauth/token`** have a specific JSON structure in their response as below:
```
{
"response": {},
"successful": true
}
```
The SnappPay driver implemented in this project has followed this structure and is checking the `successful` boolean property first (throwing an exception if it's false), then returning the `response` property as result in all public methods. But this convention has been ignored in the `eligible` method. The `successful` property check is absent, and it's returning the entire json body instead of the `response` property.
I submitted this PR to follow the same convention for returning results in all public methods. I am aware that this change may introduce a breaking change, so please let me know how you handle these kind of …

Return response from SnappPay::eligible

---

README-FA.md
README-ZH.md
README.md
composer.json
config/payment.php
src/Drivers/Pna/Pna.php

https://github.com/shetabit/payment/issues/315
درایور درگاه به صورت انلاین تست شده و اوکی هست. 
تنها مسئله ای که وجود داره این هست که لینک برگشت به صورت post کال میشه و در لاراول باید در middleware مربوط به csrf لینک کال بک ایگنور بشه
این دو مسئله را دوست داشتم یکجا داکیومنت کنم ولی نمیدونستم کجا باید اضافه بشه.

افزودن درگاه پرداخت نوین

---

config/payment.php
src/Drivers/Zarinpal/Strategies/Sandbox.php

- **Chore:**
- Updated the Zarinpal sandbox URLs in the configuration file to align with the latest sandbox environment changes.
- **Refactor:**
- Replaced the outdated SOAP web service with the new REST API in the Zarinpal Sandbox strategy, following the official documentation changes from Zarinpal ([reference](https://next.zarinpal.com/paymentGateway/sandbox.html)).
This refactor resolves the breaking issues when using the Zarinpal gateway in sandbox mode, ensuring compatibility and smooth payment testing.

[Chore] Update Zarinpal Sandbox URLs and Refactor API Integration

---

src/Drivers/SEP/SEP.php

SEP gateway's verify method returns some additional info about the Terminal and Transaction. 
```
TerminalId
OrginalAmount(Amount)
AffectiveAmount
StraceDate
```
This PR adds all the additional parameters to the receipt. 
Using verify will only check for `RefNum` parameter. This feature adds the ability to check for paid amount after verify.
Also if merchant have multiple gateway terminals, the TerminalNumber value can be used to separate payments for different terminals.

Add additional parameters for SEP gateway

---

src/Drivers/Zibal/Zibal.php

Replaced the HTTP client code with cURL to handle API requests for the Zibal payment gateway. The change aims to streamline the request process, encapsulating the data and headers setup within the cURL functions.

Switch to cURL for API requests in Zibal driver

---

config/payment.php
src/Drivers/Payping/Payping.php

از آنجایی که در ورژن ۳ تمامی لینک های مربوط به وب سرویس تغییر کرده است و نام فیلد های برگشتی هم تغییر داشته برای حفظ سازگاری نرم افزار با ورژن های قبلی مجبور هستیم که یک کانفیگ جدید به درایور پی پینگ اضافه کنیم. و بر اساس اون درخواست ها را تغییر بدیم. 
در صورتیکه کاربران ورژن های قبلی قصد دارند به ورژن جدید پی پینگ ارتقا بدن سیستم باید در فایل کانفیگ پارامتر های درایور پی پینگ را به این شکل تغییر بدن
```
'apiPurchaseUrl' => 'https://api.payping.ir/v3/pay/',
'apiPaymentUrl' => 'https://api.payping.ir/v3/pay/start/',
'apiVerificationUrl' => 'https://api.payping.ir/v3/pay/verify/',
'version'=>'3'
```

Add PayPing version 3 support

---

composer.json

سلام
وقتتون بخیر
از اونجایی که دیگه php7 منسوخ شده و همه پکیج‌های معروف php هم به نسخه 8 و  بالاتر آپدیت شدن بنظرم بهتره توی این پکیج هم آپیدت انجام بدید و یه major release انجام بشه.

update php version and other dependencies

---

src/Contracts/ReceiptInterface.php

We have this issue where we don't have access to the receipt details right after verifying payment!
**Motivation for the Change**
1. **Standardization:** These additions align the ReceiptInterface with the Receipt implementation, ensuring all details are accessible through the defined interface methods.
2. **Flexibility:** Provides a built-in way for users to retrieve metadata stored in detail() without requiring dedicated getters for each specific key.
3. **Code Consistency:** Brings parity between the concrete Receipt class (which uses HasDetail) and its contract, making it clear that details and metadata are part of the core functionality.
4. **Improved Usability:** Users can now access and manipulate transaction metadata more easily through methods that adhere to the interface, …

Add: receipt details to ReceiptInterface

---

src/Drivers/SnappPay/SnappPay.php

Hi,  
This pull request adds a **10-second timeout** to the `eligible` method of SnappPay. This method is called when a user want selects a payment gateway. 
Previously, if the API connection failed or was slow, the method would hang indefinitely since it had no timeout. Adding a timeout improves reliability and prevents delays in the payment process.

Add Timeout to `eligible` Method in SnappPay

---

src/Drivers/Saman/Saman.php

Description
Added **transaction ID verification** to the Saman payment driver's verify() method to **prevent double spending and replay attacks**. The implementation compares the stored transaction ID with the 'ResNum' parameter returned from the payment gateway. If they don't match, the transaction is automatically reversed using the ReverseTransaction SOAP method and an appropriate error is thrown with code -101.
Motivation and context
This change is required to address a critical security vulnerability in the payment flow. Without this verification, an attacker could potentially replay a successful payment response or process the same payment multiple times, leading to financial losses.
The implementation prevents these security risks by ensuring that the transaction ID created during …

Fix: Prevent double spending and replay attacks in Saman payment driver

---

src/Drivers/SEP/SEP.php
src/Drivers/Saman/Saman.php

This PR addresses two issues in the SEP payment driver:
1. Adds amount verification to ensure that the transaction amount returned from the SEP gateway exactly matches the expected invoice amount, with proper currency adjustment
2. Updates the transaction ID to use `ResNum` instead of `RefNum` as per SEP documentation, ensuring we use the correct identifier for transactions
Specifically, the changes:
- Add verification logic comparing the invoice amount with the `AffectiveAmount` returned from SEP
- Apply currency multiplier (×10) when currency is set to 'T'
- Add a new error code (-107) when amounts don't match
- Update receipt creation to use `ResNum` as the `transactionId` instead of `RefNum` based on SEP documentation
- Preserve `RefNum` in the receipt details for reference
These …

Fix: amount verification and correct transaction ID in SEP payment driver

---

src/Drivers/SEP/SEP.php
src/Drivers/Saman/Saman.php

This PR addresses a critical security vulnerability in payment validation that could potentially allow double spending. The issue occurs because we're not properly verifying that the transaction ID stored in the invoice matches the incoming `refNum` from the payment gateway response.
Specifically, the changes:
- Add validation logic to compare the transaction ID stored in the invoice against the incoming `refNum`
- Implement proper error handling when transaction IDs don't match
- Add rejection mechanism for requests with previously used transaction IDs to prevent double spending
- Add additional security checks to ensure payments are processed only once per valid transaction ID
This fix is critical for payment security and integrity. Without proper validation of transaction IDs against …

Fix: Double spending vulnerability in Sep payment driver

---

src/Drivers/Zibal/Zibal.php

Keep getDetail('orderId') and getDetail('order_id') for backward compatibility

Generate order id using getUuid() method instead of getDetail('orderId')
