shetabit/multipay

- src/Drivers/Parsian/Parsian.php
> Fix invalid token in Parsian driver

- src/Drivers/Zibal/Zibal.php
Added optional description value to the $data array in Zibal driver.
This addition allows users to send an optional description for their zibal payment..)
> Add description to zibal driver

- src/Drivers/Pasargad/Utils/RSA.php
Fix error for Pasargad driver on php 7.4
Accourding to this issue, the bug for Pasargad driver on php 7.4 fixed:
https://github.com/shetabit/payment/issues/113
> Fix error on Pasargad driver for php 7.4

- README-FA.md
- README-ZH.md
- README.md
- config/payment.php
- src/Drivers/Sepehr/Sepehr.php
Added Sepehr( Bank Saderat ) gateway.
this driver tested on the server is working successfully.
> Add Sepehr( Bank Saderat ) gateway

- src/Drivers/Behpardakht/Behpardakht.php
Add status translator array for converting status to a readable message.
For Better error handling
I test translator for multiple error messages with banktest.ir
> Behpardakht translator

- src/Drivers/Behpardakht/Behpardakht.php
Avoiding rollback money if transaction was already verified, settled or reversed in Behpardakht driver.
If you don't properly handle request in verify callback URL page, by refreshing verify page, rollback money method called due a verify error.
> Behpardakht Avoiding rollback money if transaction was already verified, settled or reversed.

- src/Drivers/Sepehr/Sepehr.php
fix bug when call function in sepehr gateway in verify section
> fix bug when call function in sepehr gateway in verify section

- src/Drivers/Sepehr/Sepehr.php
in verify function fixed check failed error 
**all way tested and worked successful**
> fix bug in verify not success in Sepehr(Saderat) gateway

- src/Drivers/Asanpardakht/Asanpardakht.php
- src/Drivers/Behpardakht/Behpardakht.php
- src/Drivers/Saman/Saman.php
- src/Drivers/Sepehr/Sepehr.php
fix send cellphone number for show users card number in gateway page in
- Saman
- Behpardakht
- AsanPardakht
- Sepehr
fixed this  #39
> handle send cellphone number in Saman, Behpardakht, AsanPardakht, Sepehr

- src/RedirectionForm.php
Change toJson method to return response with correct http header.
> Change toJson method

- src/Payment.php
This pull request will fix https://github.com/shetabit/payment/issues/167
> Fix `Payment::callbackUrl`

- src/Drivers/Sadad/Sadad.php
Add additional payment info to receipt `detail` bag for Sadad driver
new additional fields are:
- orderId
- traceNo
- referenceNo
- description
they are available via `$receipt->getDetail()` method
This pull request is related to 
https://github.com/shetabit/payment/issues/168
If …
> Add additional payment info to receipt for Sadad driver

- src/Drivers/Asanpardakht/Asanpardakht.php
Add additional payment info to receipt `detail` bag for Asanpardakht driver
new additional fields are:
- traceNo
- referenceNo
- transactionId
- cardNo
they are available via `$receipt->getDetail()` method
This pull request is related to 
https://github.com/shetabit/payment/issues/168
Please, please, please, don't send your pull request until all of the boxes are ticked. Once your pull request is created, it will trigger a build on our [continuous integration](http://www.phptherightway.com/#continuous-integration) server to make sure your [tests and code style pass](https://help.github.com/articles/about-required-status-checks …
> Add additional payment info for Asanpardakht driver

- README.md
Correct a grammatical error: 
<- if it's not exists
-> If it doesn't exist
> Correct a grammatical error

- config/payment.php
- src/Drivers/Payir/Payir.php
رفع باگ مربوط به درگاه پی دات آی ار و بروررسانی کدهای خطا
> fix payir gateway bug and update error codes

- src/RedirectionForm.php
This pull request will fix https://github.com/shetabit/multipay/issues/67
> Change return type of `toJson` method to plain json

- src/Drivers/Sadad/Sadad.php
this section has given a bad variable for show response, in Sadad's document this section handle by a capital letter.
[https://sadadpsp.ir/file/attach/202002/654.pdf](url)  page: 13
> fix sadad detail in response

- src/Drivers/Sadad/Sadad.php
Describe your changes in detail.
If it fixes an open issue, please link to the issue here (if you write `fixes #num`
or `closes #num`, the issue will be automatically closed when the pull is accepted.)
fixes #72 
Please describe in detail how you tested your changes.
Include details of your testing environment, and the tests you ran to
see how your change affects other areas of the code, etc.
- [ x] Bug fix (non-breaking change which fixes an issue)
Please, please, please, don't send your pull request until all of the boxes are ticked. Once your pull request is created, …
> fix verify api change in sadad (#72)

- src/Drivers/Local/Local.php
> fix number_format parameter count

- src/Drivers/Behpardakht/Behpardakht.php
add details to "Behpardakht" receipt
We needed extra details about "Behpardakht" Driver so we followed your conventions and added some details.
This change follows current conventions in this project and was tested with care.
If you're unsure about any of these, don't hesitate to …
> add details to "Behpardakht" receipt

- src/Drivers/Behpardakht/Behpardakht.php
Added Conditional Statements to check for Http2 and Http1.1
Solve error for http1.1 on SOAP-ERROR: Encoding: Cannot find encoding
> Solved new error on http1.1

- src/Receipt.php
> fix tiny bug

- src/Drivers/Behpardakht/Behpardakht.php
this solves the problem where http_version is not set
tested in docker environment and local beta test server
> fix behpardakht http version detection

- src/Drivers/Zarinpal/Strategies/Normal.php
Today I got "Undefined index: message" again which was previously fixed
> Fix "Undefined index: message"

- README-FA.md
- README-ZH.md
- README.md
- config/payment.php
- src/Drivers/Sepordeh/Sepordeh.php
> Add Sepordeh driver

- config/payment.php
- src/Drivers/Nextpay/Nextpay.php
> nextpay corrections

- src/Drivers/Behpardakht/Behpardakht.php
سلام وقت بخیر
ممنون از زخمات شما بابت این پکیج عالی
من امروز داشتم درگاه  بانک ملت رو بابت ارسال شماره موبایل جهت نمایش شماره کارت های کاربر هنگام پرداخت تست میکردم که دیدم نمایش نمیده. و مشکل داره. یعنی فقط refid رو ارسال میکنه دیگه شماره موبایل رو نمیفرسته. داکیومنت های خود به پرداخت رو دیدم و بعد اومدم در قسمت
vendor\shetabit\multipay\src\drivers\behpardakht
درایور رو هم بررسی کردم که دیدم مشکل  از  این قسمت هست
if (!empty($this->invoice->getDetails()['mobile'])) {
$data['mobileNo'] = $this->invoice->getDetails()['mobile'];
}
باید $data['mobileNo']   به $data['MobileNo']  تغییر پیدا کنه. یعنی فقط  حروف m مربوط به mobile باید بزرگ بشه Mobile
تغییر رو انجام دادم و تست هم کردم درست شد.
البته من این پکیج رو برای لاراول استفاده میکنم که دیدم این فایل ها در پروژه payment نیست که بخوام اون رو …
> fixed input name mobileNo TO MobileNo for behpardakht driver

- config/payment.php
- src/Drivers/Rayanpay/Rayanpay.php
Add New Driver to Repo name as RayanPay Website : https://rayanpay.com
> Add rayan pay

- README.md
- config/payment.php
- src/Drivers/Sizpay/Sizpay.php
Tested and payment completed successfully
> Add Sizpay driver

- README.md
- config/payment.php
- src/Drivers/Vandar/Vandar.php
> Add Vandar driver

- src/Drivers/Pasargad/Pasargad.php
check invoice transaction amount with the amount which user must be payed and throw exception if numbers doesn’t  match
recently one of our clients encountered a problem with this critical security bug. the attacker opens two transactions one for price of 10,000 Rials and another for 10,000,000 Rials. after successfully paying the first transaction, he simply cancels the second one and capture its iN, and replace it with the first transaction. so it means that you simply pay 10,000 Rials but get 10,000000.
so i just need to check the amount of the payed transaction which will be retrieved with **apiCheckTransactionUrl** and check the amount with my transaction price.
- [x ] Bug fix (non-breaking change …
> Fix pasargad tref

- src/Drivers/Saman/Saman.php
تنظیمات soap به تابع purchase هم باید اضافه میشد
> add missed soap config in saman purchase

- src/Contracts/ReceiptInterface.php
- src/Drivers/Payping/Payping.php
- src/Drivers/Vandar/Vandar.php
added the missing responses & cardNumber in verify receipt for vandar & payping
> Add additional info to Vandar & Payping 

- src/Drivers/Zibal/Zibal.php
اضافه شدن آیتم تسهیم و پارامتر‌های مربوطه به درگاه پرداخت زیبال.
> Added multiplexingInfos and related parameters to Zibal driver

- src/Drivers/Azki/Azki.php
Tiny fix
- check if not set fall back url in config file, set call back url
- convert amount items from toman to rial
> Tiny Fix of AzkiVam gateway

- README-FA.md
- README.md
- config/payment.php
- src/Drivers/SEP/SEP.php
SEP (Saman Electronic Payment) driver for Keshavarzi & Saderat gateways.
Add support for SEP custom fields (up to 4) 
Update en/fa README files
> SEP driver

- src/Drivers/Azki/Azki.php
BugFix: check exist items on purchase method.
> [fix] fix condition of check exist items

- config/payment.php
change Azki API URL to **azkivam.com**.
> update Azki api url.

- README.md
- config/payment.php
- src/Drivers/Payfa/Payfa.php
Added [payfa](https://payfa.com/) getaway driver  
It has been tested with the new veriosn of pyfa API and it's working correctly. 
What types of changes does your code introduce? Put an `x` in all the boxes that apply:  
Go over all the following points, and put an `x` in all the boxes that apply.  
Please, please, please, don't send your pull request until all of the boxes are ticked. Once your pull request is created, it will trigger a build on our [continuous integration](http://www.phptherightway.com/#continuous-integration) server to make sure your [tests and code style pass](https://help.github.com/articles/about-required-status-checks/).  
> Added Payfa driver

- src/Drivers/Zibal/Zibal.php
Update Payment Exception Zibal For Status Code and Message
Fix Payment Exception Zibal For Status Code and Message
Yes, Tested
> Update Driver Zibal

- src/Drivers/Zarinpal/Strategies/Normal.php
In order to handle internet timeouts inside Iran just removed the checking 101 status code
> Remove handling of 101 Status code

- src/Drivers/Nextpay/Nextpay.php
- Fix reference id in verify
- Added some missing invoice details
> Update nextpay driver

- config/payment.php
- src/Drivers/Irankish/Irankish.php
Hello dear Khanzadi,
The previous driver of IranKish was completely changed and I updated it to the latest version based on the [official document](https://www.irankish.com/page/download_module) of its website and tested it with real data and everything OK.
Thanks
> Upgrade Irankish driver to V9

- config/payment.php
- src/Drivers/Asanpardakht/Asanpardakht.php
* Handle paymeny currency (Rial, Toman)
Add currency in payment config for Asanpardakht driver. 
I handle currency in Rial and with Asanpardakht driver, multiply 10 to convert amout to Rial!
If it fixes an open issue, please link to the issue here (if you write `fixes #180`
or `closes #180`, the issue will be automatically closed when the pull is accepted.)
Please, please, please, don't send your pull request until all of the boxes are ticked. Once your pull request is created, it will trigger a build on our [continuous …
> Update Asanpardakht driver (#180)

- src/Drivers/Nextpay/Nextpay.php
- اضافه شدن کد وضعیت 
- نرمال سازی پیام های بازگشتی در وریفای پرداخت
در وریفای پرداخت و رخ دادن خطا، اکسپشن ایجاد شده کد خطا درگاه رو برگشت نمیداد و بصورت پیشفرض همیشه 0 برمیگرداند و علاوره بر این نرمال سازی هم روی پیام های بزگشتی اتفاق نیفتاده بود
متاسفانه چون بزرگواران در نکس پی تفکیک کدهای خطا رو انجام ندادن، من هم به ناچار برای اینکه حالتی از قلم نیوفته همه وضعیت ها رو در کد اوردم که در اینده اگه لیست دقیق کد های خطا برای این مرحله رو بدست بیارم PR دیگه ثبت میکنم
> Added status code and normalization messages in response to payment verify (Nextpay)

- config/payment.php
- src/Drivers/Sadad/Sadad.php
Add PaymentByMultiIdentity mode to sadad
Add currency setting to sadad
Some code style fixing
> Add PaymentByMultiIdentity mode to sadad

- config/payment.php
- src/Drivers/Aqayepardakht/Aqayepardakht.php
- src/Drivers/Asanpardakht/Asanpardakht.php
- src/Drivers/Atipay/Atipay.php
- src/Drivers/Azki/Azki.php
- src/Drivers/Behpardakht/Behpardakht.php
- src/Drivers/Digipay/Digipay.php
- src/Drivers/Fanavacard/Fanavacard.php
- src/Drivers/Idpay/Idpay.php
- src/Drivers/Irankish/Irankish.php
- src/Drivers/Nextpay/Nextpay.php
- src/Drivers/Omidpay/Omidpay.php
- src/Drivers/Parsian/Parsian.php
- src/Drivers/Pasargad/Pasargad.php
- src/Drivers/Payfa/Payfa.php
- src/Drivers/Payir/Payir.php
- src/Drivers/Payping/Payping.php
- src/Drivers/Paystar/Paystar.php
- src/Drivers/Poolam/Poolam.php
- src/Drivers/Rayanpay/Rayanpay.php
- src/Drivers/SEP/SEP.php
- src/Drivers/Saman/Saman.php
- src/Drivers/Sepehr/Sepehr.php
- src/Drivers/Sepordeh/Sepordeh.php
- src/Drivers/Sizpay/Sizpay.php
- src/Drivers/Vandar/Vandar.php
- src/Drivers/Zarinpal/Strategies/Normal.php
- src/Drivers/Zarinpal/Strategies/Sandbox.php
- src/Drivers/Zarinpal/Strategies/Zaringate.php
- src/Drivers/Zibal/Zibal.php
Based on this issue (https://github.com/shetabit/multipay/issues/193), I have added the default currency to most of the driver configurations, except for Etebarino, Paypal, Walleta, and Yekpay. This is because I do not know their default currencies, and it is not clear in the code. I will attempt to refactor this feature in the future.
> Add default currency to config

- src/Drivers/Aqayepardakht/Aqayepardakht.php
- src/Drivers/Atipay/Atipay.php
- src/Drivers/Digipay/Digipay.php
- src/Drivers/Idpay/Idpay.php
- src/Drivers/Irankish/Irankish.php
- src/Drivers/Local/Local.php
- src/Drivers/Parsian/Parsian.php
- src/Drivers/Payfa/Payfa.php
- src/Drivers/Payir/Payir.php
- src/Drivers/Paypal/Paypal.php
- src/Drivers/Payping/Payping.php
- src/Drivers/Paystar/Paystar.php
- src/Drivers/Poolam/Poolam.php
- src/Drivers/Rayanpay/Rayanpay.php
- src/Drivers/SEP/SEP.php
- src/Drivers/Saman/Saman.php
- src/Drivers/Sepehr/Sepehr.php
- src/Drivers/Sepordeh/Sepordeh.php
- src/Drivers/Sizpay/Sizpay.php
- src/Drivers/Vandar/Vandar.php
- src/Drivers/Yekpay/Yekpay.php
Fix this issue (https://github.com/shetabit/payment/issues/256)
> Set suitable error code in InvalidPaymentException

- src/Drivers/Irankish/Irankish.php
Hello, dear Mahdi
There was an error related to SSL in the IranKish gateway, Then I solved by adding an option to this driver.
> Fix Irankish ssl error

- config/payment.php
- src/Drivers/Behpardakht/Behpardakht.php
implement cumulative status key to Behpardakht global setting. by setting **_cumulativeDynamicPayStatus_** to true. method bpCumulativeDynamicPayRequest will be called.
This pull request adds a new class called CumulativePayRequest. This class represents a request for cumulative pay, which is a type of pay that is calculated based on the total amount of pay that an employee has received over a period of time.
you can refer to Behpardakht documentation for more details. 
> Cumulative pay request

- src/Drivers/Nextpay/Nextpay.php
سلام
طبق مشکلی که در [https://roocket.ir/discuss/%D9%85%D8%B4%DA%A9%D9%84-%D8%AF%D8%B1-%D9%BE%DA%A9%DB%8C%D8%AC-shetabit-%D8%AF%D8%B1%DA%AF%D8%A7%D9%87-%D9%86%DA%A9%D8%B3%D8%AA-%D9%BE%DB%8C](https://roocket.ir/discuss/%D9%85%D8%B4%DA%A9%D9%84-%D8%AF%D8%B1-%D9%BE%DA%A9%DB%8C%D8%AC-shetabit-%D8%AF%D8%B1%DA%AF%D8%A7%D9%87-%D9%86%DA%A9%D8%B3%D8%AA-%D9%BE%DB%8C) گفته شده و طبق مستنداتی که در [https://github.com/shetabit/payment/issues/225](https://github.com/shetabit/payment/issues/225) ارسال شده، مقدار message در رسپانس وجود نداره و اصلاح شد.
> Fix Nextpay bug

- README-FA.md
- README-ZH.md
- README.md
- config/payment.php
- src/Drivers/Bitpay/Bitpay.php
Code tested by BitPay's test API docs. ([https://bitpay.ir/codes/PDF/api-test-V4.pdf](https://bitpay.ir/codes/PDF/api-test-V4.pdf))
> add bitpay driver

- src/Drivers/Paystar/Paystar.php
Correct the currency for the Paystar driver in the verify method.
> fix paystar currency

- config/payment.php
- src/Drivers/Jibit/Jibit.php
Currency added to jibit gateway. 
(Following #218 PR)
> Add currency to Jibit gateway

- composer.json
- composer.lock
composer.json updated based on this issue.
[https://github.com/shetabit/multipay/issues/222](https://github.com/shetabit/multipay/issues/222)
> fix chillerlan/php-cache version to support php8

- src/Drivers/Digipay/Digipay.php
Hi, 
fix https://github.com/shetabit/multipay/pull/228#discussion_r1518675000
and update Exception message of `verify` method.
> [fix] update error message, and ensure variable exist on Digipay gateway

- config/payment.php
Corrected the api-secret key-name for Jibit driver in payment config file.
#232 
It is tested by Jibit payment gateway.
> [Fix]: Corrected the api-secret key-name for Jibit driver in payment config file.

- config/payment.php
- src/Drivers/Minipay/Minipay.php
Minipay provides credit for shopping for enterprise users.
I've added our IPG system driver to Multipay package.
>  add minipay driver

- README-FA.md
- README-ZH.md
- README.md
- composer.json
- config/payment.php
- src/Drivers/Gooyapay/Gooyapay.php
گویاپـــی ، پرداخت یار رسمی بانک مرکزی
فراتر از یک درگاه پرداخت
> add Gooyapay Driver

- src/Drivers/Behpardakht/Behpardakht.php
- src/Drivers/Zarinpal/Strategies/Normal.php
- src/Drivers/Zarinpal/Strategies/Sandbox.php
- src/Drivers/Zarinpal/Strategies/Zaringate.php
- src/Drivers/Zibal/Zibal.php
Describe your changes in detail.
If it fixes an open issue, please link to the issue here (if you write `fixes #num`
or `closes #num`, the issue will be automatically closed when the pull is accepted.)
Please describe in detail how you tested your changes.
Include details of your testing environment, and the tests you ran to
see how your change affects other areas of the code, etc.
Please, please, please, don't send your pull request until all of the boxes are ticked. Once your pull request is created, it will trigger a build on our [continuous …
> decrease complexity

- src/Drivers/Digipay/Digipay.php
some time key `code` not returned from gateway.
> [fix] check array key exist on response Digipay Gateway

- src/Drivers/SnappPay/SnappPay.php
Hi, convert `externalSourceAmount` to correct currency.
> [fix] fix price of externalSourceAmount before send to SnappPay Gateway

- README-FA.md
- README-ZH.md
- README.md
سلام
موقع کپی کامند نصب پکیج علامت $ اضافه است و کپی میشه که پاک شد.
> remove $ from package installation command in readme

- src/Drivers/Toman/Toman.php
This pull request replaces the use of (Laravel's Http class !!!!) with the GuzzleHttp client in Toman driver.
> replace laravel Http class with GuzzleHttp

- src/Request.php
Fix return types for get and post methods in Request class
> Fix Request class return types

- src/Drivers/Zibal/Zibal.php
سلام برای درگاه زیبال تست گرفتم خطای 500 برگشت داده میشد از سمت درگاه کد رو به این شکل تغییر دادم درست شد
> fix zibal gateway 500 response

- src/Drivers/Zibal/Zibal.php
- src/Exceptions/PreviouslyVerifiedException.php
- src/Payment.php
Hi,  
In this pull request, I have refactored the **Zibal driver**, implementing all features according to the [official documentation](https://help.zibal.ir/IPG/API/). Additionally, I replaced raw **cURL** requests with **Guzzle**, making the gateway request handling more readable and maintainable.  
1. **Improved Parameter Handling:**  
- Introduced an `optionalField` key to allow passing additional parameters such as `multiplexingInfos`, `feeMode`, `nationalCode`, and others.  
- These optional fields are merged with the main request dynamically.  
2. **Enhanced Receipt Data:**  
- The generated receipt now includes **all response data** from the verify method, such as `cardNumber`, `paid_at`, `orderId`, etc.  
3. **Order ID Handling:**  
- According to the documentation, `orderId` is …
> Refactor zibal gateway

- composer.json
- phpstan.neon.dist
- src/Drivers/Atipay/Core/fn.atipay.php
- src/Drivers/Irankish/Irankish.php
- src/Drivers/Jibit/JibitClient.php
- src/Drivers/Payping/Payping.php
- src/Drivers/Rayanpay/Rayanpay.php
- src/Request.php
سلام
پکیج https://github.com/phpstan/phpstan برای آنالیز کد و رفع باگ های احتمالی نصب شد و خطاهای سطح یک رفع گردید.
هر خطا در یک کامیت فیکس شده تا راحت تر بتونید بررسی کنید و عنوان کامیت هم متن خطایی بود که داده شده بود.
> Add phpstan

- README.md
add description on how to usage receipt details in verify method to README file
> Add: receipt details usage to README

- src/Drivers/Saman/Saman.php
debug saman driver for reverse transaction in Toman currency
just add a condition for currency
> fix: debug saman driver for reverse transaction in Toman currency

- src/Drivers/Gooyapay/Gooyapay.php
سلام، وقت بخیر
https://github.com/shetabit/payment/issues/342#issuecomment-2885960216
> Fix InvalidPaymentException
